name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Newman
        run: npm install -g newman
      - name: Run API tests
        run:  newman run https://www.getpostman.com/collections/24513725-5c4a8fb5-3953-45f4-93e0-045c63cce930 -e https://www.getpostman.com/environments/24513725-775dc746-81ce-4c95-8449-fac68da17cc1 --global-var "apiKey=PMAK-65f689cf6b3f3d0001f43e8f-280a0aed394632cb987ba99a527a3c1c60"
